###
POST  http://127.0.0.1:8000/api/subject/19/create
Content-Type: application/json

{
    "count" : 3
}
###

POST http://127.0.0.1:8000/api/subject/8/project/42/productbacklog-create
Content-Type: application/json

{
    "count" : 3
}