# Generated by Django 4.1.5 on 2024-01-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectall', '0003_subject_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
