# Generated by Django 4.1.5 on 2024-01-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectall', '0004_subject_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='figma_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='trello_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
