# Generated by Django 4.1.5 on 2024-01-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectall', '0006_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='id_student',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
