# Generated by Django 4.1.5 on 2024-01-28 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectall', '0010_productbacklogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255)),
                ('task_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('doing', 'Doing'), ('done', 'Done')], default='todo', max_length=5)),
                ('product_backlogs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectall.productbacklogs')),
            ],
        ),
    ]
