# Generated by Django 4.1.5 on 2024-01-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectall', '0011_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='amount',
        ),
        migrations.AddField(
            model_name='subject',
            name='project_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
