# Generated by Django 4.1.5 on 2024-01-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectall', '0014_rename_group_name_project_project_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id_student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.AddField(
            model_name='appuser',
            name='id_student',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
