# Generated by Django 4.1.5 on 2024-01-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectall', '0015_remove_student_first_name_remove_student_id_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='id_student',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
