# Generated by Django 4.1.5 on 2024-01-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectall', '0016_alter_appuser_first_name_alter_appuser_id_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbacklogs',
            name='title_product',
            field=models.CharField(default='', max_length=255),
        ),
    ]
