# Generated by Django 4.1.5 on 2024-02-03 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectall', '0017_productbacklogs_title_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='users',
            new_name='members',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='amount',
        ),
    ]
