# Generated by Django 4.1.5 on 2024-02-09 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectall', '0019_rename_productbacklogs_productbacklog_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
