# Generated by Django 4.1.5 on 2024-02-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectall', '0020_rename_tasks_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbacklog',
            name='important',
            field=models.CharField(choices=[('mid', 'mid'), ('low', 'low'), ('hight', 'hight')], default='low', max_length=5),
        ),
        migrations.AlterField(
            model_name='productbacklog',
            name='status',
            field=models.BooleanField(choices=[(False, 'todo'), (False, 'doing'), (True, 'done')], default='todo'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.BooleanField(choices=[(False, 'todo'), (False, 'doing'), (True, 'done')], default='todo'),
        ),
    ]
