# Generated by Django 4.1.5 on 2024-02-18 03:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectall', '0021_alter_productbacklog_important_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_done',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='task',
            name='date_to_do',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('STD', 'Student'), ('TCH', 'Teacher')], default='STD', max_length=255),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
