# Generated by Django 4.1.5 on 2024-02-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectall', '0022_task_date_done_task_date_to_do_alter_appuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbacklog',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
