# Generated by Django 4.1.5 on 2024-02-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectall', '0023_productbacklog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbacklog',
            name='hour_done',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productbacklog',
            name='hour_todo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='hour_done',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='hour_todo',
            field=models.IntegerField(default=0),
        ),
    ]
