# Generated by Django 4.1.5 on 2024-02-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectall', '0024_productbacklog_hour_done_productbacklog_hour_todo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbacklog',
            name='status',
            field=models.BooleanField(choices=[('todo', 'todo'), ('doing', 'doing'), ('done', 'done')], default='todo'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.BooleanField(choices=[('todo', 'todo'), ('doing', 'doing'), ('done', 'done')], default='todo'),
        ),
    ]
