# Generated by Django 4.1.5 on 2024-02-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectall', '0025_alter_productbacklog_status_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbacklog',
            name='status',
            field=models.CharField(choices=[('todo', 'todo'), ('doing', 'doing'), ('done', 'done')], default='todo', max_length=5),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'todo'), ('doing', 'doing'), ('done', 'done')], default='todo', max_length=5),
        ),
    ]
