# Generated by Django 4.1.5 on 2024-02-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectall', '0026_alter_productbacklog_status_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='id_student',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='productbacklog',
            name='important',
            field=models.CharField(choices=[('midium', 'midium'), ('low', 'low'), ('hight', 'hight')], default='low', max_length=6),
        ),
    ]
