# Generated by Django 4.1.5 on 2024-02-24 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectall', '0027_task_id_student_alter_productbacklog_important'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyscrum',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectall.project'),
        ),
        migrations.AddField(
            model_name='dailyscrum',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectall.subject'),
        ),
    ]
