# Generated by Django 4.1.5 on 2024-02-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectall', '0028_dailyscrum_project_dailyscrum_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyscrum',
            name='note',
            field=models.CharField(choices=[('วันนี่ทำงาน', 'วันนี่ทำงาน'), ('ป่วย', 'ป่วย'), ('ติดธุระ', 'ติดธุระ'), ('ตกลงกันว่าวันนี้ไม่ทำงาน', 'ตกลงกันว่าวันนี้ไม่ทำงาน')], max_length=255),
        ),
    ]
