# Generated by Django 4.1.5 on 2024-03-01 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectall', '0030_alter_dailyscrum_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyscrum',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
